### ISSUE TITLE
Consider use absolute path

### ISSUE THREAD

**Issue by Puriney** [ygidtu/sashimi.py#52]
I set the absolute path for the bam files to feed `--density`. But the problem is that the bash command line version always take it as the relative path by default. It always add the current working folder before the path. 

Could you modify the bash version `sashimipy` to recognize the absolute path?

**Comment by ygidtu** [comment]
Hi there,
    The absolute path should work, so could your please provide more information ? For example, what's your density list looks like and the detailed error message. If you could provide an example data would be much helpful.

Best wish.

**Comment by Puriney** [comment]
```
$ cat i.density.txt
~/project/DATA/s7/ATAC/mapping_result/s7.positionsort.MAPQ30.bam	bam	ATAC
~/project/DATA/s7/ChiSE/mapping_result/s7.positionsort.MAPQ30.bam	bam	ChiSE
```
Error:
```
2022-11-17 02:28:57.566 | INFO     | sashimi.plot:set_region:178 - set region to chr17:39679000-39684000:+
2022-11-17 02:28:57.566 | ERROR    | sashimi.cli:process_file_list:220 - /volumes/USR1/yyan/project/ABC/s7/test_sashimipy/i.density.txt -> /volumes/USR1/yyan/project/ABC/s7/test_sashimipy/~/project/DATA/s7/ATAC/mapping_result/s7.positionsort.MAPQ30.bam not found.
```

Run:
```
$ sashimipy \
--density ~/project/ABC/s7/test_sashimipy/i.density.txt \
-e chr17:39679000-39684000:+ \
-r /volumes/seq/genomes/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf \
--choose-primary --raster \
--output ~/project/ABC/s7/test_sashimipy/sashimi.pdf
```

**Comment by Puriney** [comment]
It will add file prefix to the input absolute path. 
```
/volumes/USR1/yyan/project/ABC/s7/test_sashimipy/~/project/DATA/s7/ATAC/mapping_result/s7.positionsort.MAPQ30.bam not found.
```

**Comment by zhou-ran** [comment]
Hi Yun,
Replace "~/" to absolute path in your config file, and we'll update a new version for this situation,

Best,
Ran

**Comment by zhou-ran** [comment]
Hi Yun,
Replace "~/" to absolute path in your config file, and we'll update a new version for this situation,

Best,
Ran

**Comment by ygidtu** [comment]
Hi,
   I see the problems now, I'll try to release a fix version as soon as possible.
   And here is an walk around method for you to run the sashimipy, please try to replace the `~` at the begining of each file path to your home directory as Ran said.
Best,

**Comment by Puriney** [comment]
Great. Thank you.
