### ISSUE TITLE
KeyError: 'transcript_name'

### ISSUE THREAD

**Issue by Puriney** [ygidtu/sashimi.py#53]
Hello, 
My GTF file from ucsc does not contain `transcript_name`. When I set `-r <path_to_gtf>`, it reports the error: 

```
  File "/volumes/USR1/yyan/anaconda3/envs/r_env/lib/python3.10/site-packages/sashimi/file/Reference.py", line 373, in __load_gtf__
    transcript=rec.transcript_name,
  File "pysam/libctabixproxies.pyx", line 638, in pysam.libctabixproxies.GTFProxy.__getattr__
KeyError: 'transcript_name'
``` 

I noticed the Transcript object does not create transcript_name by default. Not sure if this is relavant. 

https://github.com/ygidtu/sashimi.py/blob/afa2ceabf79b16d093baa668a43d2bb382a29a30/sashimi/base/Transcript.py#L43-L44

Or is there any other parameters of `sashimipy` for me to use?

**Comment by Puriney** [comment]
```
$ head genes.gtf
chr1	unknown	exon	11874	12227	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018_1"; gene_name "DDX11L1"; tss_id "TSS14523";
chr1	unknown	exon	12613	12721	.	+	.	gene_id "DDX11L1"; transcript_id "NR_046018_1"; gene_name "DDX11L1"; tss_id "TSS14523";
```

**Comment by ygidtu** [comment]
Hi Yun,
    The `sashimi.py` has options to draw transcript names instead of ids, therefore we need the transcript name by default. I draft an new develop version should solve your problem currently. 

Before we draft new version of `sashimi.py`, please try to use the source code instead of the command line version.

The source code could be download by using following commands
```bash
git clone git@github.com:ygidtu/sashimi.py.git sashimipy
cd sashimipy
git checkout dev
python main.py
```

Best

**Comment by ygidtu** [comment]
Hi Yun,
 I draft a new release v0.0.7, which solves your file path issues and this KeyError. 
 Please try with new version of sashimi.py

Best Wishes,
Yiming

**Comment by ygidtu** [comment]
Hi Yun,
   It has been a while since the last reply, I will close this issue, welcome to re-open if you still have questions
Best Wishes,
Yiming
