### ISSUE TITLE
Assorted dumb questions considering sashimi and stranded libraries

### ISSUE THREAD

**Issue by ckuenne** [ygidtu/sashimi.py#60]
i have now played around with the sashimi tool and came up with the following.

this was a paired-end stranded/rev library and i set the config file like this:

sashimi_config.tsv:
```
m2.bam	bam	m2	#377EB8	frf
```

command:
```
sashimipy -r homo_sapiens.104.mainChr.gtf -e chr15:72782652-72798451:+ -p 8 -d 300 --density sashimi_config.tsv -o sashimi_1.pdf --show-junction-num --density-by-strand
```

result:
[sashimi_1.pdf](https://github.com/ygidtu/sashimi.py/files/10216737/sashimi_1.pdf)

now to my questions:
1. is this the correct way to set the library mode for stranded/rev (="frf")? and if i had a stranded/for library i would set this to "frs"? are there other valid library modes?
2. what does the event strand actually do? “-e chr1:100-200:+” / “-e chr1:100-200:-“ lead to identical plots.
3. is it possible to just show the sashimi plot junction numbers for pairs of one strand? or draw the +strand arcs on top and the -strand ones below, similar to the way --density-by-strand works for the density? my workaround for now would be to split the bam file by strand and just run it twice, but is there a built-in solution for this?
4. sometimes when you have a junction that spans beyond the current plot range you set it to start at zero. but the first big junction in my example goes way further to the left in reality. this is quite misleading. and sometimes you also seem to draw an open arc in this case, which would be the ideal way. is this a bug?

best,
carsten

**Comment by ygidtu** [comment]
Hi carsten,
   1. Yes, you're right for the 1st question, 'fru' is another valid parameter which means unstrand library.
   2. The strand is just a text label between the transcripts and plots, it's a little bit confusing, we're considering make it more flexible in next version.
   3. For current version, sashimi.py could not done that, thanks for your advice, we're working on it now.
   4. We try to use an open arc represent the junction that spans beyond the plot range. For the situation that junction start from zero, we'll look closer to see if there are some bugs left behind.
   Recently, both of us may have covid19, so the development progress may be slightly slow, if there is corresponding progress, we will reply you as soon as possible.

Best,
Yiming Zhang & Ran Zhou

**Comment by ckuenne** [comment]
thx for the quick answer, this is helpful. 

considering 4.: i ran the whole thing again with a bam file split by strand. and it seems to me like the arcs drawn below the line are always forced to 0 (=buggy) while the ones on top look ok. [sashimi_per_strand.pdf](https://github.com/ygidtu/sashimi.py/files/10225621/sashimi_per_strand.pdf)

and get well soon!

best,
carsten

**Comment by ckuenne** [comment]
and if i can make some more suggestions: it would increase readability if you used a white or opaque background for the junction numbers instead of a fully transparent one. and it would be further extremely helpful if the numbers were non-overlapping.

**Comment by ygidtu** [comment]
Hi carsten,
   Thanks for your example and suggestions, we'll check and improve it
Best,
Yiming Zhang

**Comment by ygidtu** [comment]
Hi carsten,
   I drafted version 0.1.2 with following changes.
   1. Fixed junction out of junction range
   2. Junctions from positive/negative strand separated as density while using `-- density-by-strand`
   3. Add repel for junction numbers using [adjustText](https://github.com/Phlya/adjustText), similar with [ggrepel](https://github.com/slowkow/ggrepel). But still failed with too much numbers.

Example with artificial data
<img width="683" alt="图片" src="https://user-images.githubusercontent.com/29178828/208300539-5e91ae8f-5357-4a70-98e0-284ee3be7996.png">

Too much numbers
<img width="622" alt="图片" src="https://user-images.githubusercontent.com/29178828/208300663-f97b3c0c-6dda-49c3-adcd-55b1564b82cd.png">

For the white background, currently cannot make a satisfied repel effect, therefore I kept the transparent background for now.

Best wishes,
Yiming Zhang

**Comment by ckuenne** [comment]
hi yiming,

very quick update, thx! 

i first checked the behaviour of 0.12 with my old plot with "--density-by-strand" and bams already separated by strand. and there is still something wrong. for some reason either the top or bottom arc gets flattened. is this because the bams were already "by-strand"? but the flattened arc is still visible right at the horizontal line.
[sashimi_per_strand.new.pdf](https://github.com/ygidtu/sashimi.py/files/10257953/sashimi_per_strand.new.pdf)

sashimi_config.tsv:
```
#bam_path	type	label	color	library
m2.f.bam	bam	m2_f	#377EB8	frf
m2.r.bam	bam	m2_r	#377EB8	frf
```

cmd:
```
sashimipy -r homo_sapiens.104.mainChr.gtf -e chr15:72782652-72798451:+ -p 8 -d 300 --density sashimi_config.tsv -o sashimi_1.pdf --show-junction-num --density-by-strand
```

next i tried the same without "--density-by-strand". and here the flattened arc is just skipped completely, but the number is still being printed.
[sashimi_per_strand.new2.pdf](https://github.com/ygidtu/sashimi.py/files/10257952/sashimi_per_strand.new2.pdf)

- - - 

next try with a full bam (so NOT split by strand).

with "--density-by-strand": arcs seem to be drawn more or less randomly above/below the line, independent of the strand.
[sashimi.new.pdf](https://github.com/ygidtu/sashimi.py/files/10257951/sashimi.new.pdf)

without "--density-by-strand": the below-line arcs seem to get suppressed in general now. and there is a strange artefact at the very left side of the plot.
[sashimi.new2.pdf](https://github.com/ygidtu/sashimi.py/files/10257955/sashimi.new2.pdf)

seems like the bug writer did his job. ;)

**Comment by ygidtu** [comment]
Hi carsten,
    Thanks for you test case, it's really helpful. I have fixed your problems, like increase the buffer region at top and bottom of density plot to make sure all the junctions will display correctly. And the `disappeared` junctions seems just overlap with each other, therefore I manually adjust the junction coordinates.
   Here are several examples.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/29178828/209421019-a44556c4-af80-4bc4-a55f-f17bfd126f0c.png">
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/29178828/209421022-af250f9a-760b-4939-b9fc-0125eb3810fc.png">
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/29178828/209421034-72990ccd-086f-439a-895f-774a60d93a43.png">

Best

**Comment by ckuenne** [comment]
hi yiming,

i recreated all plots with version 0.1.5 and everything works perfectly now. thx!

best,
carsten
